management.endpoints.web.exposure.include = *
management.info.env.enabled = true
spring.application.name=bjjtracker

info.app.name = "BjjTracker"
info.app.description = "My Martial Arts Training Session Tracker"
info.app.version = "0.1"

server.port = 8080
